### ISSUE TITLE
Need a reference to SN.FreshDesk.Models

### ISSUE THREAD

**Issue by derekantrican** [syron/SN.FreshDesk#19]
Can't call the `fd.CreateTicket` method without a reference to `SN.FreshDesk.Models`. What am I missing?

![image](https://user-images.githubusercontent.com/1558019/50111946-ce844880-01f2-11e9-8d39-80821bda4e04.png)

**Comment by MarkMilfordMe** [comment]
Hi @derekantrican 

Did you resolve this issue or is it still a problem?

Thanks

**Comment by derekantrican** [comment]
I haven't used this in a very long time. I'll close and reopen if I ever get back to this (and see the issue again)
